spring:
  application:
    name: campaign

  datasource:
    url: jdbc:h2:mem:campaign;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  jpa:
    database: h2
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /console

---
spring.config.activate.on-profile: sandbox

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
